---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: farm-server
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAxYsD5kc/L53wdRE2wvlIoUkFOjBcVsKqN4gg7vL8EUaV2nycQYV+T3Z+Joj9m4amQbHrvEAC1kGN8qxGNfERZznDY8FlxrOO/bcOJExzQOyPKKx3eSO33U3FMV/YX5aVHeSMGcjrkj9eefPMaHyUtAaL47agS8UOU3LzDSnZeh1NNyVhVwZm4iM1dfVv5fCNROGKsBjEqaMp8jdSmVjfFCx0i4Wrx3VtR2YeOXLWMKRH35rKmq35JTmw9E33j8X1OjyXMia/770LzEk9VxBk/AkWfkUfL37vW3k9eWbD2/IuN0722G5DYcR9C6o9SCPPcRkYz70+/EvS9djT0f/yIGBeBXoLnLjnn9UWTEzbbNqZwHDthmN+7+ZpHPmyL5XnAVBUylcvECv0qrXL2M/MMLL/Od8d0ji08yq2TXrQtJXve1lBv3vKfEBuC9xpbqorKRe3Q9c8sJaiVebKmIFxdcB2MFo5dM8PnweBMYn09D1DkI56lRWct0iX5V+IiHMR/OpHDKtC5wKPuxEQCpM3C4ECJ/l7vqtiJTKz/7LpoTikTyxqKhp0giTbu1klk9Wa+U13oAGT84sN2vLArxXDRtSyB57dKbVVXtYbauu57XzdED/W2KSaohr1Q47pHVACxpQk6A0Ekq5sLqnLAkb2FMJi1XhWSw5eV9ky5prid/jrqfb7uqsVDnIYx0pAhjmMHYNdqT3rhJLW1OadV
    MINIO_ROOT_USER: AgA9A8zW4VEV2u3MwUmGpCb0iG62MxZKoN9+jhMQiHOvM1/5SGF0WUHHCVkq6u13SvG1WRUt0Hu69TUUjUi9vlUa8K75ijtLjFp7M1mnrOGoPpKwmSeG6CW4NkIjj/ai054uVD9ZaUnG6lS0fGsAb++aK+jTZxXVqQ+nui1QuS3GxrSjRSPoyK4obYXhAuE5uadnWSwHvQESnV2UFGOfhdsPgbLUJR0wv89QdpCOSQmF6YJ0sVBhNgS7Cghp/3tmkg+U1iJVo4x2QJYiP/06TNQodTXXoUnl4H0P31F8l4vyn9uOfB4g5cFaNya4i0WwgdbhJmaByI+B54pE4GwEh/SAVJ9x/dfFrfd4ufl/CDywvdDaSugz/W0kite1lwxuKedehfHO8c1IagyBMYcSMFEVdTM53ujM+kOWf7XyoOzU5XQYKXfQ6Q7ynxSWSvIYKvmDCrpFen9OCvhkQj5k+pddyw6lj5yJi38FolZRriyDSwd8u4TU+3Diopi0hZWknL96aHTnrjzaQRHCAX6cfOafr0muqe6FOCaUVNmt6zOowvK0nKB+Qet16AFojcwzK5YPlW6GNGbbPNFiABkf0Yaj3F8CZCEpvQIvq/G3bqGKll4QUXWmVVHjSX+ozQxEUJ3xOGoDhrJiYvmBhRFcKRYJTWlaViBm7pIusm9+8ejWTA44fZZXbbNPlrp54lKuJMW1cFHMC9M1LHw=
  template:
    metadata:
      name: minio-secret
      namespace: farm-server
