apiVersion: v1
kind: Service
metadata:
{{ include "htop.header" . | indent 2}}
spec:
  selector:
    app: htop-{{ .Release.Name }}
  type: NodePort
  ports:
    - port: 7682
      targetPort: 7682
      nodePort: 30682