---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: farm-server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA3MIetCsvUeI8P8cpyPw6Ix3tnn8wou6jlKwZL7v6MS3q+Fbw7Yqrf6RvcZU5R/uP+OKncKv48I8GAHfoQ8nKYSnIpnamAgdLL/S7pXmhM/+GkN7C2Ic9UqSR2ABIbDKGOJjfSenjeDIIgyCtNeJuXIuIn6eKLNor4MGv8s9VV9h3CqazEj0UNThcG7zH7uofZ1bQeTMgv5+NTwSgkIrFSUEC4kpLcF5Dh5rK79nrSxccrGZleN0NYjDWgOSM2UVld7RmL3vQCUnxWiVaLD8dNkqOnvdrXC9Vf57aZxsrHi31vrLvKd7jKyJVncsRlfPJkU0JnGS8UnAM3vYXueWjqBJAvR7Zlu+jM8heim8bq95DQqs/kCLTc3oxqBNq56tQqdx4u0Y+CYO8I4h1ayJPkkiMMS++QWLwTCZph2VXq82wF+g9tQyg44kAEFP/SdZUL/Uki1d4pXx666mytThD18PpTxwYvVn8uDBZabEzrauQbAJFiBCoLQmhIKuM3eQrgLmTt5fsvLAJGaRwP43e/j4mER8JjdumpheUyi7wCgLfBSFNzc+ZRDTutC7LTGJsUvoajqgUzP7t6QP2nGwKe/XXzBxHj+LC6GmCwlKBEs1py05KXJzGYXGpG8G7FOOU4n3QfIpy3HO6bMx99uvyod8IkQKOCbQEFqeWLcMtwY1K4YhTphK4HR0OTpOgKiw2FIwy1kS4vXXsn3C/QFlM4
    POSTGRES_USER: AgCMUY2R9B5+kFsgK3WzpusEuYDoeY57L/93kAv951aauSy7Uar3eCjOMPliOrOlu1uzJkYfzyvpK4MJF4NKEBnHQSIeP5IDQzHO6wyhID4woXd0xIVyuJ0SyM1+iIXUoO6o/8B6EY3/LWcyAci2FBj+WXrW8h1bctXowja1iD6B6XgoMxGjvuj1XddCOYnp3jFe5EsNyFWuvLBQ5K9IK3VCs63SF7bwZEbKoZhB9Kxi08taAp9Z8z1HLK8rDQ/bwgL4LL6WsIgHUhC+cwPy1XAQUFlVAD3ewf6EWqa+ZsgXuGTtcSRSy1FrCUdwIZauYukpUfOoxv3J9oFClpJEYAtaiBfyPjygUKxpwcpMW3UE5FizCZeHiT87EYQJfrHcQMdNC4/Z9hvqtfKebayf7OXC4H+jSZETRnGcAT90AfNJX9so0HBR2JD18HZsWE1u2nvHC9oSKUZ4rA1bYfxMK/mNbRwZYhxhWsF5WdShcYgQyAykYJH/fxVvhoohH+AnA4FsoG4ewRKze6WKZnxpNEEouewfvaCIQxlCXrLnTNYGqIzLTCQMucLE7w+zRbK1kWQT+r5k8Uvy1iqSCwbZyDg4cyx44kcvr+8sMrw6PUXGrILKPNFM5rPUekv0MPx2EPS/nG1qY68XLxpuSi3VLcASrEi9Ve/khmDMEYMkUjv83wOfulxs7Mw5mozotr0gz/+uQEqLMemC1sl9U9I=
  template:
    metadata:
      name: postgres-secret
      namespace: farm-server
