apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jyga-minio.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.service.consolePort }}"
          ports:
            - containerPort: {{ .Values.service.apiPort }}
            - containerPort: {{ .Values.service.consolePort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: {{ .Values.service.apiPort }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: {{ .Values.service.apiPort }}
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: data
{{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "jyga-minio.fullname" . }}
{{- else }}
          emptyDir: {}
{{- end }}