{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret

metadata: 
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.secret.labels.app }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.secret.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secret.auth.rootPassword | quote }}
{{- end }}