apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jyga-minio.fullname" . }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}