apiVersion: v1
kind: Service
metadata:
  name: {{ include "jyga-minio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
