---
apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-envs
  namespace: {{ .Release.Namespace }}
  labels:
    app: batch
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.profile }}
  batch.datasource.ml.farm.url: {{ .Values.config.datasourceUrl }}
  farm.s3.endpoint: {{ .Values.config.s3EndPoint }}
  