---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-cronjob
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.config.schedule }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 900
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:                  
            - name: ecr-pull-secret
          containers:
            - name: batch-container
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }} 
              envFrom:
                - configMapRef:
                    name: batch-envs
              env:
                - name: batch.datasource.ml.farm.username
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret    # ← Secret déjà créé par postgres
                      key: POSTGRES_USER
                - name: batch.datasource.ml.farm.password
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret    
                      key: POSTGRES_PASSWORD
                - name: farm.s3.access-key
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret       # ← Secret déjà créé par minio
                      key: MINIO_ROOT_USER
                - name: farm.s3.secret-key
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: MINIO_ROOT_PASSWORD