apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-deployment
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: batch
  strategy:
    type: Recreate
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: batch 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      serviceAccountName: default
      imagePullSecrets:                  # 👈 Ajouter ici
        - name: ecr-pull-secret  
      containers:
        - name: batch-container
          image: 215734518063.dkr.ecr.ca-central-1.amazonaws.com/vision-system-batch-ml:0.1.9-rc
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: batch-envs 