
  config:
    profile: dev
    datasourceUrl: jdbc:postgresql://postgres-service:5432/machine_learning_farm
    datasourceUsername: postgres
    datasourcePassword: postgres
    s3AccessKey: admin
    s3SecretKey: admin@2026
    s3EndPoint: http://minio-instance-minio.svc.cluster.local:9000
    
  aws:
    accessKey: ""
    secretKey: ""
    region: ca-central-1