apiVersion: v2
name: jyga-minio
description: MinIO deployment (Chainguard hardened image)
type: application
version: 0.1.0
appVersion: "RELEASE"

dependencies:
  - name: jyga_base
    version: "0.1.0"
    repository: "https://lwtchami.github.io/helmcharts"

keywords:
  - minio
  - s3
  - object-storage

maintainers:
  - name: JYGA Team
