{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Values.secret.labels.app}}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
type: Opaque
{{- end }} 