apiVersion: v1
kind: Service
metadata:
{{ include "btop.header" . | indent 2}}
spec:
  selector:
    app: btop-{{ .Release.Name }}
  type: NodePort
  ports:
    - port: 7681
      targetPort: 7681
      nodePort: 30681